#!/usr/bin/env python3
"""
Emit the TLB-mapped code segments as C arrays for the host.

Conker's hand-written code reads lookup tables stored inside its own TLB-mapped
code pages (e.g. 0x150AA318), and the debugger reads its rodata at 0x1600xxxx.
The host copies these arrays to the matching addresses in the runtime's memory
at startup (host/src/overlays.cpp). Words are emitted as N64 32-bit values,
which is the runtime's in-memory layout on a little-endian host.

The symbols file gives each section's address and size; the bytes come from the
unpacked ROM (recomp/unpack_rom.py, without the code rewrites), so the copy is
exactly what the game had.

The same arrays give mods the uncompressed code that RECOMP_HOOK needs (the
runtime recompiles a hooked function from its original instructions; .game is
compressed in the ROM). For that, each segment's ROM address in the recompiled
layout (N64Recomp's section rom_addr) is emitted too, along with the words
recomp/code_rewrites.txt changes in all code sections (.init included), so a
hooked function is rebuilt from the same instructions as the rest of the game.

Usage: emit_tlb_pages.py <syms.toml> <unpacked.bin> <code_rewrites.txt> <out.c>
"""
import re
import struct
import sys

SEGMENTS = [(".game", "conker_game_segment"), (".debugger", "conker_debugger_segment")]


def sections(syms_path):
    text = open(syms_path, encoding="utf-8").read()
    return {m.group(1): (int(m.group(2), 16), int(m.group(3), 16), int(m.group(4), 16))
            for m in re.finditer(r'\[\[section\]\]\nname = "([^"]*)"\nrom = (0x[0-9A-F]+)\n'
                                 r'vram = (0x[0-9A-F]+)\nsize = (0x[0-9A-F]+)', text)}


def main(syms_path, image_path, rewrites_path, out_path):
    secs = sections(syms_path)
    image = open(image_path, "rb").read()
    out = ["// Generated by recomp/emit_tlb_pages.py from the original code. Do not edit.",
           "#include <stdint.h>", "#include <stddef.h>", ""]
    for sec, sym in SEGMENTS:
        rom, vram, size = secs[sec]
        words = struct.unpack_from(f">{size // 4}I", image, rom)
        out.append(f"const uint32_t {sym}_vram = 0x{vram:08X};")
        out.append(f"const uint32_t {sym}_rom = 0x{rom:08X};")
        out.append(f"const size_t {sym}_size = 0x{size:X};")
        out.append(f"const uint32_t {sym}[] = {{")
        for k in range(0, len(words), 8):
            out.append("    " + ", ".join(f"0x{w:08X}" for w in words[k:k + 8]) + ",")
        out.append("};")
        out.append("")
    # The words recomp/code_rewrites.txt changes, by ROM address.
    out.append("const uint32_t conker_code_rewrites[][2] = {")
    count = 0
    for line in open(rewrites_path, encoding="utf-8"):
        m = re.match(r'([0-9A-F]{8}) ([0-9A-F]{8})\s+#\s*(\S+) (0x[0-9A-F]{8})', line)
        if m:
            out.append(f"    {{ 0x{m.group(1)}, 0x{m.group(2)} }}, // {m.group(3)} {m.group(4)}")
            count += 1
    out.append("};")
    out.append(f"const size_t conker_code_rewrite_count = {count};")
    out.append("")
    open(out_path, "w", newline="\n").write("\n".join(out))


if __name__ == "__main__":
    if len(sys.argv) != 5:
        sys.exit(__doc__)
    main(*sys.argv[1:])
