#!/usr/bin/env python3
"""
Writes the recompiler's committed inputs from the decompilation (developers only;
recomp/run.sh runs it): recomp/conker.us.syms.toml, the symbols file N64Recomp
recompiles the ROM's code with, and recomp/code_rewrites.txt, the instructions
recomp/prepare_elf.py changes. With those, building the game only needs the ROM
(recomp/recompile.py), not the decompilation's toolchain.

The symbols file is N64Recomp's --dump-context of the prepared ELF, adjusted so
that recompiling from it gives exactly the same code and tables as from the ELF:
- every ELF section is listed, in the ELF's order, so the section indices (and
  num_sections) stay the same; the ones without functions (data, the header, the
  symbol tables) with no functions. Jump tables are read from the data sections.
- recomp_entrypoint, at the KSEG0 alias 0x80001000 of .init's first function,
  gets its ROM address directly (N64Recomp can't compute it from .init's vram).
- where two names share an address (func_150ADA20 / random_u32), the descriptive
  one comes first: it's the one calls resolve to, as with the ELF.

The rewrites are the words where the prepared ELF's code differs from the ROM's.

Usage: make_syms.py <prepared.elf> <dump.toml> <unpacked.bin> <syms_out.toml> <rewrites_out.txt>
"""
import re
import struct
import sys


def elf_sections(data):
    shoff, = struct.unpack_from(">I", data, 0x20)
    shentsize, shnum, shstrndx = struct.unpack_from(">HHH", data, 0x2E)
    shdrs = [struct.unpack_from(">10I", data, shoff + i * shentsize) for i in range(shnum)]
    strtab = shdrs[shstrndx][4]
    phoff, = struct.unpack_from(">I", data, 0x1C)
    phentsize, phnum = struct.unpack_from(">HH", data, 0x2A)
    phdrs = [struct.unpack_from(">8I", data, phoff + i * phentsize) for i in range(phnum)]
    sections = []
    for sh in shdrs:
        name = data[strtab + sh[0]:data.index(b"\0", strtab + sh[0])].decode()
        rom = 0
        for p_type, p_offset, _, p_paddr, p_filesz, *_ in phdrs:
            if p_type == 1 and sh[5] and p_offset <= sh[4] < p_offset + p_filesz:
                rom = p_paddr + sh[4] - p_offset
        loaded = sh[1] == 1 and (sh[2] & 2)  # PROGBITS, SHF_ALLOC
        sections.append({"name": name, "vram": sh[3], "offset": sh[4], "size": sh[5] if loaded else 0,
                         "rom": rom, "code": bool(sh[2] & 4)})
    return sections


def dump_functions(dump):
    funcs = {}
    for m in re.finditer(r'\[\[section\]\]\nname = "([^"]*)"\n.*?functions = \[\n(.*?)\n\]', dump, re.S):
        funcs[m.group(1)] = [l for l in m.group(2).split("\n") if l.strip()]
    return funcs


def main(elf_path, dump_path, image_path, syms_out, rewrites_out):
    elf = open(elf_path, "rb").read()
    image = open(image_path, "rb").read()
    sections = elf_sections(elf)
    funcs = dump_functions(open(dump_path).read())

    entry = r'\{ name = "recomp_entrypoint", vram = 0x80001000, size = (0x[0-9A-F]+) \},'
    for name, lines in funcs.items():
        for i, line in enumerate(lines):
            m = re.search(entry, line)
            if m:
                del lines[i]
                sec = next(s for s in sections if s["name"] == name)
                lines.insert(0, f'    {{ name = "recomp_entrypoint", vram = 0x80001000, rom = 0x{sec["rom"]:08X}, '
                                f'size = {m.group(1)} }},')
                break
        # Aliases: descriptive names before func_XXXXXXXX ones at the same address.
        vram_of = lambda l: re.search(r'vram = (0x[0-9A-F]+)', l).group(1)
        i = 0
        while i < len(lines) - 1:
            if vram_of(lines[i]) == vram_of(lines[i + 1]) and '"func_' in lines[i] and '"func_' not in lines[i + 1]:
                lines[i], lines[i + 1] = lines[i + 1], lines[i]
            i += 1

    out = ["# The code of Conker's Bad Fur Day (US) for N64Recomp: sections, functions and their",
           "# sizes. Generated from the decompilation by recomp/make_syms.py (recomp/run.sh):",
           "# don't edit by hand. No game data: the code itself comes from your ROM.", ""]
    for sec in sections:
        out += ["[[section]]", f'name = "{sec["name"]}"', f'rom = 0x{sec["rom"]:08X}', f'vram = 0x{sec["vram"]:08X}',
                f'size = 0x{sec["size"]:X}', ""]
        lines = funcs.get(sec["name"])
        out += ["functions = ["] + lines + ["]", ""] if lines else ["functions = []", ""]
    open(syms_out, "w", newline="\n").write("\n".join(out))

    rewrites = ["# Instructions recomp/prepare_elf.py changes for the recompiler (ROM address in the",
                "# unpacked image, new word), applied by recomp/unpack_rom.py. Generated by",
                "# recomp/make_syms.py."]
    for sec in sections:
        if not sec["code"] or not sec["size"]:
            continue
        for k in range(0, sec["size"], 4):
            ours = elf[sec["offset"] + k:sec["offset"] + k + 4]
            if ours != image[sec["rom"] + k:sec["rom"] + k + 4]:
                word, = struct.unpack(">I", ours)
                rewrites.append(f"{sec['rom'] + k:08X} {word:08X}  # {sec['name']} 0x{sec['vram'] + k:08X}")
    open(rewrites_out, "w", newline="\n").write("\n".join(rewrites) + "\n")
    print(f"make_syms: {sum(len(v) for v in funcs.values())} functions, {len(rewrites) - 3} rewrites")


if __name__ == "__main__":
    if len(sys.argv) != 6:
        sys.exit(__doc__)
    main(*sys.argv[1:])
